# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecount',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
