# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170501_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
