# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_exitcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraficTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('entry_count', models.IntegerField()),
                ('exit_count', models.IntegerField()),
            ],
        ),
    ]
