# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_trafictimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafictimes',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trafictimes',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
