# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20170630_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafictimes',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.Location'),
            preserve_default=False,
        ),
    ]
